# Model configuration
model:
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

# Training configuration
training:
  batch_size: 4
  learning_rate: 1.0e-4
  max_epochs: 100
  checkpoint_callback:
    every_n_train_steps: 1000

# Data configuration
data:
  target: ldm.data.imagenet.ImageNetTrain
  params:
    size: 256
    root: "/path/to/dataset"
    batch_size: 4
    num_workers: 4

# Optimizer configuration
optimizer:
  target: torch.optim.AdamW
  params:
    lr: 1.0e-4
    betas: [0.9, 0.999]
    weight_decay: 0.01

# Scheduler configuration
scheduler:
  target: torch.optim.lr_scheduler.CosineAnnealingLR
  params:
    T_max: 100000

# Logging configuration
logging:
  log_dir: "/path/to/logs"
  tensorboard: true

# Inference configuration
inference:
  steps: 50
  guidance_scale: 7.5